ktu_gallery_homepage:
    path: /
    defaults: { _controller: KTUGalleryBundle:Album:albums }

ktu_gallery_user_albums:
    path: /albums/
    defaults: { _controller: KTUGalleryBundle:Album:userAlbums }

ktu_gallery_album:
    path: /album/{id}
    defaults: { _controller: KTUGalleryBundle:Album:album }
    requirements:
        id:  \d+

ktu_gallery_photo:
    path: /photo/{id}
    defaults: { _controller: KTUGalleryBundle:Photo:showPhoto }
    requirements:
        id:  \d+

ktu_gallery_search:
    path: /search
    defaults: { _controller: KTUGalleryBundle:Tag:search }

ktu_search_results:
    path: /search/{name}
    defaults: { _controller: KTUGalleryBundle:Tag:results }

ktu_search_post:
    pattern: /s
    defaults: { _controller: KTUGalleryBundle:Tag:post }

ktu_comment_post:
    pattern: /comment/post/{id}
    defaults: { _controller: KTUGalleryBundle:Comment:post, id: 0 }
    requirements:
        id:  \d+

ktu_comment_form:
    pattern: /comment/{id}
    defaults: { _controller: KTUGalleryBundle:Comment:form, id: 0 }
    requirements:
        id:  \d+

ktu_comment_delete:
    pattern: /admin/comment/delete/{id}
    defaults: { _controller: KTUGalleryBundle:Comment:delete }
    requirements:
        id:  \d+

ktu_photo_like:
    pattern: /photo/like/{id}
    defaults: { _controller: KTUGalleryBundle:Like:photoLike }
    requirements:
        id:  \d+

ktu_photo_form:
    pattern: /admin/photo/{id}
    defaults: { _controller: KTUGalleryBundle:Photo:form, id: 0 }
    requirements:
        id:  \d+

ktu_photo_delete:
    pattern: /admin/photo/delete/{id}
    defaults: { _controller: KTUGalleryBundle:Photo:delete }
    requirements:
        id:  \d+

ktu_photo_post:
    pattern: /admin/photo/post
    defaults: { _controller: KTUGalleryBundle:Photo:post }

ktu_photo_edit:
    pattern: /admin/photo/edit/{id}
    defaults: { _controller: KTUGalleryBundle:Photo:edit, id: 0 }
    requirements:
        id:  \d+

ktu_album_form:
    pattern: /admin/album/{id}
    defaults: { _controller: KTUGalleryBundle:Album:form, id: 0 }
    requirements:
        id:  \d+

ktu_album_delete:
    pattern: /admin/album/delete/{id}
    defaults: { _controller: KTUGalleryBundle:Album:delete }
    requirements:
        id:  \d+

ktu_album_post:
    pattern: /admin/album/post/{id}
    defaults: { _controller: KTUGalleryBundle:Album:post, id: 0 }
    requirements:
        id:  \d+
