parameters:
    ktu_gallery.album_service.class: KTU\GalleryBundle\Service\AlbumService
    ktu_gallery.photo_service.class: KTU\GalleryBundle\Service\PhotoService
    ktu_gallery.user_provider.class: KTU\GalleryBundle\Service\UserProvider

services:
    ktu_gallery.album_service:
        class: %ktu_gallery.album_service.class%
        arguments: [@doctrine.orm.entity_manager]

    ktu_gallery.photo_service:
        class: %ktu_gallery.photo_service.class%
        arguments: [@doctrine.orm.entity_manager]

    ktu_gallery.user_provider:
        class: %ktu_gallery.user_provider.class%
        arguments: [@fos_user.user_manager,{facebook: facebook_id}]
