nfqakademija_gallery_homepage:
    path: /
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:index }

nfqakademija_galleryadmin_homepage:
    path: /admin/
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:index }

nfqakademija_album_form:
    pattern: /admin/album/form/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:form, id: 0 }
    requirements:
            id:  \d+

nfqakademija_album_delete:
    pattern: /admin/album/delete/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:delete }
    requirements:
            id:  \d+

nfqakademija_album_post:
    pattern: /admin/album/
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:post }