nfqakademija_gallery_homepage:
    path: /
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:index }

nfqakademija_gallery_album:
    path: /album/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:index }
    requirements:
                id:  \d+

nfqakademija_photo_form:
    pattern: /admin/photo/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:form, id: 0 }
    requirements:
            id:  \d+

nfqakademija_photo_delete:
    pattern: /admin/photo/delete/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:delete }
    requirements:
            id:  \d+

nfqakademija_photo_post:
    pattern: /admin/photo/post/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:post, id: 0 }
    requirements:
            id:  \d+

nfqakademija_album_form:
    pattern: /admin/album/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:form, id: 0 }
    requirements:
            id:  \d+

nfqakademija_album_delete:
    pattern: /admin/album/delete/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:delete }
    requirements:
            id:  \d+

nfqakademija_album_post:
    pattern: /admin/album/post/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:post, id: 0 }
    requirements:
            id:  \d+