nfqakademija_gallery_homepage:
    path: /
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:index }

nfqakademija_galleryadmin_homepage:
    path: /admin/
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:index }

nfqakademija_album_form:
    pattern: /admin/album/form/
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:form }

nfqakademija_album_post:
    pattern: /admin/album/
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:post }