nfqakademija_gallery_homepage:
    path: /
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:index }

nfqakademija_gallery_album:
    path: /album/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:index }
    requirements:
                id:  \d+

nfqakademija_gallery_photo:
    path: /photo/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:showPhoto }
    requirements:
                id:  \d+

nfqakademija_gallery_search:
    path: /search/{name}
    defaults: { _controller: NFQAkademijaGalleryBundle:Tag:search }

nfqakademija_comment_post:
    pattern: /comment/post/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Comment:post, id: 0 }
    requirements:
            id:  \d+

nfqakademija_comment_form:
    pattern: /comment/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Comment:form, id: 0 }
    requirements:
            id:  \d+

nfqakademija_comment_delete:
    pattern: /admin/comment/delete/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Comment:delete }
    requirements:
            id:  \d+

nfqakademija_photo_like:
    pattern: /photo/like/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Like:photoLike }
    requirements:
            id:  \d+

nfqakademija_photo_form:
    pattern: /admin/photo/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:form, id: 0 }
    requirements:
            id:  \d+

nfqakademija_photo_delete:
    pattern: /admin/photo/delete/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:delete }
    requirements:
            id:  \d+

nfqakademija_photo_post:
    pattern: /admin/photo/post/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Photo:post, id: 0 }
    requirements:
            id:  \d+

nfqakademija_album_form:
    pattern: /admin/album/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:form, id: 0 }
    requirements:
            id:  \d+

nfqakademija_album_delete:
    pattern: /admin/album/delete/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:delete }
    requirements:
            id:  \d+

nfqakademija_album_post:
    pattern: /admin/album/post/{id}
    defaults: { _controller: NFQAkademijaGalleryBundle:Album:post, id: 0 }
    requirements:
            id:  \d+