parameters:
    nfqakademija_gallery.album_service.class: NFQAkademija\GalleryBundle\Service\AlbumService
    nfqakademija_gallery.photo_service.class: NFQAkademija\GalleryBundle\Service\PhotoService

services:
    nfqakademija_gallery.album_service:
        class: %nfqakademija_gallery.album_service.class%
        arguments: [@doctrine.orm.entity_manager]
    nfqakademija_gallery.photo_service:
            class: %nfqakademija_gallery.photo_service.class%
            arguments: [@doctrine.orm.entity_manager]