parameters:
    nfqakademija_gallery.album_service.class: NFQAkademija\GalleryBundle\Service\AlbumService

services:
    nfqakademija_gallery.album_service:
        class: %nfqakademija_gallery.album_service.class%
        arguments: [@doctrine.orm.entity_manager]